# Generated by Django 2.0.5 on 2018-05-21 04:19

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('filename', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='file',
            name='licence',
            field=models.ForeignKey(default=files.models.default_licence, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.Licence'),
        ),
    ]
