# Generated by Django 2.0.5 on 2018-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='direct_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='location',
            field=models.URLField(),
        ),
    ]
