# Generated by Django 2.0.6 on 2018-06-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180607_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=200, unique=True, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='file',
            name='location',
            field=models.URLField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
