# Generated by Django 2.0.5 on 2018-05-21 03:03

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180521_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='licence',
            field=models.ForeignKey(default=files.models.default_licence, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.Licence'),
        ),
    ]
