# Generated by Django 2.0.5 on 2018-06-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20180607_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
