# Generated by Django 2.0.6 on 2018-06-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20180608_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Location (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('files', models.ManyToManyField(blank=True, related_name='project_items', to='files.File', verbose_name='Files')),
            ],
        ),
    ]
