# Generated by Django 2.0.6 on 2018-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_projectitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='Location (URL)'),
        ),
    ]
