# Generated by Django 2.0.6 on 2018-06-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20180609_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Webpage'), (20, 'Pīkau'), (50, 'Print Media'), (99, 'Other')], default=99),
        ),
    ]
