# Generated by Django 2.0.6 on 2018-06-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_projectitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Webpage'), (20, 'Pīkau'), (50, 'Print Media'), (99, 'Other')], default=99, verbose_name='Type'),
        ),
    ]
