# Generated by Django 2.0.6 on 2018-06-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20180610_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='title',
        ),
    ]
