# Generated by Django 2.0.4 on 2018-05-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('term', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PikauCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(max_length=20)),
                ('trailer_video', models.URLField()),
                ('cover_photo', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('study_plan', models.TextField()),
                ('assessment_description', models.TextField()),
                ('assessment_items', models.TextField()),
                ('glossary_terms', models.ManyToManyField(related_name='pikau_courses', to='pikau.GlossaryTerm')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to='pikau.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pikaucourse',
            name='tags',
            field=models.ManyToManyField(related_name='pikau_courses', to='pikau.Tag'),
        ),
        migrations.AddField(
            model_name='pikaucourse',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to='pikau.Topic'),
        ),
    ]
