# Generated by Django 2.0.4 on 2018-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('exemplars', models.URLField()),
            ],
        ),
    ]
