# Generated by Django 2.0.4 on 2018-05-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0002_progressoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikaucourse',
            name='development_folder',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pikaucourse',
            name='status',
            field=models.CharField(choices=[(1, 'Conceptualising'), (2, 'Developing'), (3, 'Reviewing - Academic'), (4, 'Reviewing - Language'), (5, 'Reviewing - Technical'), (6, 'Completed'), (7, 'Completed - Published to iQualify')], default=1, max_length=60),
        ),
        migrations.AddField(
            model_name='pikaucourse',
            name='status_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('mi', 'Māori')], max_length=20),
        ),
    ]
