# Generated by Django 2.0.4 on 2018-05-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0004_auto_20180504_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikaucourse',
            name='progress_outcomes',
            field=models.ManyToManyField(related_name='pikau_courses', to='pikau.ProgressOutcome'),
        ),
    ]
