# Generated by Django 2.0.4 on 2018-05-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0005_pikaucourse_progress_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoutcome',
            name='abbreviation',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
