# Generated by Django 2.0.4 on 2018-05-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0006_progressoutcome_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='glossary_terms',
            field=models.ManyToManyField(blank=True, related_name='pikau_courses', to='pikau.GlossaryTerm'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to='pikau.Level'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='progress_outcomes',
            field=models.ManyToManyField(blank=True, related_name='pikau_courses', to='pikau.ProgressOutcome'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pikau_courses', to='pikau.Tag'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to='pikau.Topic'),
        ),
    ]
