# Generated by Django 2.0.4 on 2018-05-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0007_auto_20180506_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to='pikau.Level'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to='pikau.Topic'),
        ),
    ]
