# Generated by Django 2.0.4 on 2018-05-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0008_auto_20180506_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PikauUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('module_name', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('pikau_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pikau_content', to='pikau.PikauCourse')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pikauunit',
            unique_together={('number', 'pikau_course'), ('slug', 'pikau_course')},
        ),
    ]
