# Generated by Django 2.0.4 on 2018-05-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0008_auto_20180506_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PikauModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pikau_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pikau_modules', to='pikau.PikauCourse')),
            ],
        ),
        migrations.CreateModel(
            name='PikauUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pikau_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pikau_units', to='pikau.PikauModule')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pikauunit',
            unique_together={('slug', 'pikau_module')},
        ),
        migrations.AlterUniqueTogether(
            name='pikaumodule',
            unique_together={('slug', 'pikau_course')},
        ),
    ]
