# Generated by Django 2.0.4 on 2018-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0009_auto_20180508_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pikaumodule',
            name='content',
        ),
    ]
