# Generated by Django 2.0.4 on 2018-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0009_auto_20180509_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikauunit',
            name='module_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
