# Generated by Django 2.0.4 on 2018-05-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0010_auto_20180509_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikauunit',
            name='pikau_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='pikau.PikauCourse'),
        ),
    ]
