# Generated by Django 2.0.4 on 2018-05-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0011_auto_20180509_0724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pikauunit',
            unique_together={('slug', 'pikau_course')},
        ),
    ]
