# Generated by Django 2.0.4 on 2018-05-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0013_auto_20180509_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='assessment_items',
            field=models.TextField(blank=True),
        ),
    ]
