# Generated by Django 2.0.4 on 2018-05-09 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pikau', '0015_auto_20180509_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikaucourse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pikau_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
