# Generated by Django 2.0.4 on 2018-05-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0017_auto_20180509_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['date', 'name']},
        ),
    ]
