# Generated by Django 2.0.4 on 2018-05-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0018_auto_20180509_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikaucourse',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='_pikaucourse_prerequisites_+', to='pikau.PikauCourse'),
        ),
    ]
