# Generated by Django 2.0.4 on 2018-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0019_pikaucourse_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='postrequisites', to='pikau.PikauCourse'),
        ),
    ]
