# Generated by Django 2.0.4 on 2018-05-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0020_auto_20180514_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikaucourse',
            name='readiness_level',
            field=models.IntegerField(choices=[(1, 'Hika - Ignite'), (2, 'Māpura - Spark'), (3, 'Hahana - Glow'), (4, 'Muramura - Burn'), (5, 'Whitawhita - Blaze')], default=1),
        ),
    ]
