# Generated by Django 2.0.4 on 2018-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0021_pikaucourse_readiness_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='readiness_level',
            field=models.IntegerField(choices=[(1, '1) Hika - Ignite'), (2, '2) Māpura - Spark'), (3, '3) Hahana - Glow'), (4, '4) Muramura - Burn'), (5, '5) Whitawhita - Blaze')], default=1),
        ),
    ]
