# Generated by Django 2.0.4 on 2018-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0022_auto_20180514_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='readiness_level',
            field=models.IntegerField(choices=[(1, 'Level 1 - Hika - Ignite'), (2, 'Level 2 - Māpura - Spark'), (3, 'Level 3 - Hahana - Glow'), (4, 'Level 4 - Muramura - Burn'), (5, 'Level 5 - Whitawhita - Blaze')], default=1),
        ),
    ]
