# Generated by Django 2.0.4 on 2018-05-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0023_auto_20180514_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
