# Generated by Django 2.0.5 on 2018-05-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0026_auto_20180516_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='slug',
            field=models.SlugField(help_text='A unique readable identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pikau_courses', to='pikau.Level'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pikau_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pikau_courses', to='pikau.Milestone'),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pikau_courses', to='pikau.Topic'),
        ),
        migrations.AlterField(
            model_name='pikauunit',
            name='pikau_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content', to='pikau.PikauCourse'),
        ),
    ]
