# Generated by Django 2.0.5 on 2018-05-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0027_auto_20180522_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossaryterm',
            old_name='description',
            new_name='definition',
        ),
    ]
