# Generated by Django 2.0.5 on 2018-05-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0028_auto_20180524_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikaucourse',
            name='cover_photo',
            field=models.CharField(default='images/core-education/pikau-course-cover.png', max_length=100),
        ),
    ]
