# Generated by Django 2.0.5 on 2018-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikau', '0029_auto_20180529_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='slug',
            field=models.SlugField(help_text='A unique readable identifier', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pikaucourse',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pikauunit',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
