# Generated by Django 2.0.6 on 2018-06-09 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_projectitem'),
        ('pikau', '0031_pikaucourse_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pikaucourse',
            name='files',
        ),
        migrations.AddField(
            model_name='pikaucourse',
            name='project_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pikau_course', to='files.ProjectItem'),
        ),
    ]
